---
- name: Common setup
  hosts: all
  become: true
  roles:
    - common

- name: Docker setup
  hosts: all
  become: true
  roles:
    - docker

- name: Nginx Setup
  hosts: all
  become: true
  roles:
    - nginx
